name: Auto aktualizace zpr치v

on:
  schedule:
    - cron: '0 7 * * *'  # 7:00 UTC = 9:00 SE캛 (Praha)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: St치hni aktu치ln칤 zpr치vy
      run: |
        curl -s "https://newsapi.org/v2/top-headlines?country=cz&apiKey=27275041395845acac59c19ff0a28857" -o news.json
        echo "<!DOCTYPE html><html lang='cs'><head><meta charset='UTF-8'><title>Denn칤 p콏ehled zpr치v</title></head><body><h1>Denn칤 p콏ehled zpr치v</h1>" > index.html
        jq -r '.articles[] | "<p>游닗 " + (.title // "") + "</p>"' news.json >> index.html
        echo "</body></html>" >> index.html

    - name: Commit & push
      run: |
        git config user.name "TeemoBot"
        git config user.email "bot@teemo.com"
        git add index.html
        git commit -m "Auto aktualizace zpr치v"
        git push
